apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wg-access-server.fullname" . }}
  labels:
    {{- include "wg-access-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wg-access-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wg-access-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wg-access-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-tun
            - name: wg-as-storage-volume
              mountPath: {{ .Values.persistent.mountPath }}
              subPath: {{ .Values.persistent.subPath }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: "{{ $value }}"
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      {{- if .Values.extraVolumes }}    
        {{ toYaml .Values.extraVolumes | nindent 8}}    
      {{- end }}    
        - name: wg-as-storage-volume    
        {{- if .Values.persistent.enabled }}    
          persistentVolumeClaim:
            claimName: {{ if .Values.persistent.existingClaim }}{{ .Values.persistent.existingClaim }}{{- else }}{{ template "wg-access-server.fullname" . }}{{- end }}
        {{- end -}} 
