apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-access-server.fullname" . }}
  labels:
    {{- include "wg-access-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wg-access-server.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-access-server.fullname" . }}-wg
  labels:
    {{- include "wg-access-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWG.type }}
  ports:
    - port: {{ .Values.serviceWG.port }}
      name: wireguard
      protocol: UDP
      nodePort: {{ .Values.serviceWG.nodePort }}
      
  selector:
    {{- include "wg-access-server.selectorLabels" . | nindent 4 }}
